services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - nginx-networks
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  map_api:
    build:
      context: ./MapApi
      dockerfile: Dockerfile
    volumes:
      - ./MapApi/Static/:/app/Static
    ports:
      - "5100:5100"
    networks:
      - nginx-networks
    user: "0:0"
  auth_api:
    build:
      context: ./AuthApi
      dockerfile: Dockerfile
    ports:
      - "8100:8080"
    networks:
      - nginx-networks

networks:
  nginx-networks:
    driver: bridge
