services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-networks
    ports:
      - "9000:9000"
  map_api:
    build:
      context: ./MapApi
      dockerfile: Dockerfile
    volumes:
      - ./MapApi/Static/:/app/Static
    ports:
      - "5100:5100"
    networks:
      - nginx-networks
    user: "0:0"
  auth_api:
    build:
      context: ./AuthApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - nginx-networks

networks:
  nginx-networks:
    driver: bridge
